# Generated by Django 2.2.6 on 2020-04-02 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('background_image', models.ImageField(default='default_background.jpg', upload_to='profile_pics_background')),
                ('background_image_low', models.ImageField(default='b_img_low.png', upload_to='profile_pics_background')),
                ('description', models.TextField(max_length=251)),
                ('slug', models.SlugField(unique=True)),
                ('veryfied', models.BooleanField(default=False)),
                ('facebock', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reddit', models.URLField(blank=True, null=True)),
                ('snapchat', models.URLField(blank=True, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers1', to='System.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='following1', to='System.Profile')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends1', to='System.Profile')),
                ('from_user', models.ManyToManyField(blank=True, related_name='from_user1', to='System.Profile')),
                ('to_user', models.ManyToManyField(blank=True, related_name='to_user1', to='System.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user1', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
