# Generated by Django 2.2.6 on 2019-12-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Lorem Ipsum is simply dummy text Lorem Ipsum has been the industry'),
        ),
    ]
