# Generated by Django 2.2.6 on 2019-12-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_auto_20191223_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
