# Generated by Django 2.2.6 on 2019-12-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_auto_20191223_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='name', unique=True),
            preserve_default=False,
        ),
    ]
