# Generated by Django 2.2.6 on 2019-12-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_auto_20191225_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
