# Generated by Django 2.2.6 on 2019-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_auto_20191225_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
    ]
