# Generated by Django 2.2.6 on 2019-12-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_auto_20191226_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1, null=True),
        ),
    ]
