# Generated by Django 2.2.6 on 2019-12-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_auto_20191226_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='https://images.pexels.com/photos/877695/pexels-photo-877695.jpeg?auto=compress&cs=tinysrgb', upload_to='profile_pics_background'),
        ),
    ]
