# Generated by Django 2.2.6 on 2019-12-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_profile_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_image',
        ),
    ]
