# Generated by Django 2.2.6 on 2019-12-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_remove_profile_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='default_background.jpg', upload_to='profile_pics_background'),
        ),
    ]
