# Generated by Django 2.2.6 on 2019-12-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0015_auto_20191227_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Hi', max_length=250),
            preserve_default=False,
        ),
    ]
