# Generated by Django 2.2.6 on 2019-12-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0016_auto_20191227_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
