# Generated by Django 2.2.6 on 2019-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0017_profile_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image_low',
            field=models.ImageField(default=models.ImageField(default='default_background.jpg', upload_to='profile_pics_background'), upload_to='profile_pics_background'),
        ),
    ]
