# Generated by Django 2.2.6 on 2019-12-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_profile_background_image_low'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_image_low',
        ),
    ]
