# Generated by Django 2.2.6 on 2019-12-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0020_profile_background_image_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='veryfied',
            field=models.BooleanField(default=False),
        ),
    ]
