# Generated by Django 2.2.6 on 2019-12-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0021_profile_veryfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='youtube',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
