# Generated by Django 2.2.6 on 2020-01-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0024_auto_20200102_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends2', to='System.Profile'),
        ),
    ]
