# Generated by Django 2.2.6 on 2020-01-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0025_auto_20200107_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friendReqests',
            field=models.ManyToManyField(blank=True, related_name='friendReqests1', to='System.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends1', to='System.Profile'),
        ),
    ]
