# Generated by Django 2.2.6 on 2020-01-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0029_auto_20200107_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='to_user',
        ),
    ]
