# Generated by Django 2.2.6 on 2020-01-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0030_auto_20200107_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='from_user',
            field=models.ManyToManyField(blank=True, related_name='from_user1', to='System.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_user',
            field=models.ManyToManyField(blank=True, related_name='to_user1', to='System.Profile'),
        ),
    ]
