# Generated by Django 2.2.6 on 2020-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0031_auto_20200107_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
