# Generated by Django 2.2.6 on 2020-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0032_auto_20200131_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image_low',
            field=models.ImageField(default='default_background.jpg', upload_to='profile_pics_background'),
        ),
    ]
