# Generated by Django 2.2.6 on 2020-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0034_remove_profile_background_image_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image_low',
            field=models.ImageField(default='default_background.jpg', upload_to='profile_pics_background'),
        ),
    ]
