# Generated by Django 2.2.6 on 2020-01-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0036_auto_20200131_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_image_low',
        ),
    ]
