# Generated by Django 2.2.6 on 2020-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0038_profile_background_image_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
