# Generated by Django 2.2.6 on 2020-01-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0039_profile_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image2',
        ),
    ]
